# Generated by Django 5.1.4 on 2024-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_tunisia_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_my_tek', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
