# Generated by Django 3.1.12 on 2024-12-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
